name: Private NPM
description: Sets up NPM/Yarn to access private repositories
author: https://github.com/seek-jobs
public: true
requirements:
  - bash
configuration:
  definitions:
    scoped-registry:
      type: object
      properties:
        scope:
          type: string
        registry:
          type: string
  properties:
    registry:
      type: string
    token:
      type: string
    env:
      type: string
    file:
      type: string
    output-path:
      type: string
    scope-package-registries:
      type: array
      items:
        $ref: "#/definitions/scoped-registry"
  oneOf:
    - required:
        - file
    - required:
        - env
